# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: tf-ado-deploy-infra

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      # 'main' branch: PRD environment
      - template: ../../config-infra-prod.yml
  - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
      # 'develop' or feature branches: DEV environment
      - template: ../../config-infra-dev.yml

trigger: none

pool:
  vmImage: ubuntu-20.04

resources:
  repositories:
    - repository: Mlops-Demo-ADO # Template Repo
      name: Mlops-Demo-ADO
      type: git
      ref: main

stages:
  - stage: CreateStorageAccountForTerraformState
    displayName: Create Storage for Terraform
    jobs:
      - job: CreateStorageForTerraform
        displayName: Create Storage for Terraform
        steps:
          - checkout: self
            path: s/
          - task: Bash@3
            displayName: "Create checkout repository folder(s)"
            inputs:
              targetType: "inline"
              script: |
                set -e
                mkdir "$(Build.Repository.Name)"
                mkdir "Mlops-Demo-ADO"
          - checkout: Mlops-Demo-ADO
            path: s/templates/
          - template: templates/infra/create-resource-group.yml@Mlops-Demo-ADO
          - template: templates/infra/create-storage-account.yml@Mlops-Demo-ADO
          - template: templates/infra/create-storage-container.yml@Mlops-Demo-ADO
  - stage: DeployAzureMachineLearningRG
    displayName: Deploy AML Workspace
    jobs:
      - job: DeployAMLWorkspace
        displayName: Deploy Terraform
        steps:
          - checkout: self
            path: s/
          - task: Bash@3
            displayName: "Create checkout repository folder(s)"
            inputs:
              targetType: "inline"
              script: |
                set -e
                mkdir "$(Build.Repository.Name)"
                mkdir "Mlops-Demo-ADO"
          - checkout: Mlops-Demo-ADO
            path: s/templates/
          - template: templates/infra/create-sp-variables.yml@Mlops-Demo-ADO
          - template: templates/infra/install-terraform.yml@Mlops-Demo-ADO
          - template: templates/infra/run-terraform-init.yml@Mlops-Demo-ADO
          - template: templates/infra/run-terraform-validate.yml@Mlops-Demo-ADO
          - template: templates/infra/run-terraform-plan.yml@Mlops-Demo-ADO
          - template: templates/infra/run-terraform-apply.yml@Mlops-Demo-ADO
